export const PANTONE_COLORS = [
  {"id":"C001","pantone":"00-0002 TPG","name":"Phantom Black","zhName":"极致深黑","hex":"#050505","cat":"Urban Tech","application":"主料 (X-Pac/Cordura)"},
  {"id":"C002","pantone":"01-0006 TPG","name":"Deep Obsidian","zhName":"黑曜石","hex":"#121213","cat":"Urban Tech","application":"涂层拉链、Hypalon 辅料"},
  {"id":"C003","pantone":"02-0010 TPG","name":"Shadow Carbon","zhName":"碳纤维色","hex":"#1C1C1E","cat":"Urban Tech","application":"亚光防水面料"},
  {"id":"C004","pantone":"03-0015 TPG","name":"Matte Asphalt","zhName":"哑光沥青","hex":"#2C2C2C","cat":"Urban Tech","application":"织带、塑料扣具"},
  {"id":"C005","pantone":"03-0012 TPG","name":"Void Grey","zhName":"虚空灰","hex":"#242526","cat":"Urban Tech","application":"背板、网布"},
  {"id":"C006","pantone":"04-0017 TPG","name":"Dark Manganese","zhName":"暗锰","hex":"#303030","cat":"Urban Tech","application":"金属拉链齿、品牌 Logo"},
  {"id":"C007","pantone":"04-0020 TPG","name":"Iron Ore","zhName":"铁矿石","hex":"#383838","cat":"Urban Tech","application":"侧板拼接、内里"},
  {"id":"C008","pantone":"05-0026 TPG","name":"Titanium Dark","zhName":"暗钛","hex":"#48494B","cat":"Urban Tech","application":"反光饰条"},
  {"id":"C009","pantone":"02-0010 TPG","name":"Stealth Blue","zhName":"隐身暗蓝","hex":"#1B1E23","cat":"Urban Tech","application":"五金件"},
  {"id":"C010","pantone":"04-0014 TPG","name":"Cyber Purple","zhName":"赛博暗紫","hex":"#2E1A47","cat":"Urban Tech","application":"装饰线、铝制搭扣"},
  {"id":"C011","pantone":"07-0033 TPG","name":"Circuit Grey","zhName":"电路灰","hex":"#5E6064","cat":"Urban Tech","application":"提手缝线、拉链头绳"},
  {"id":"C012","pantone":"13-0060 TPG","name":"Silver Matrix","zhName":"矩阵银","hex":"#A9A9A9","cat":"Urban Tech","application":"急救包标识、内里拉链"},
  {"id":"C013","pantone":"03-0012 TPG","name":"Cobalt Dark","zhName":"暗钴蓝","hex":"#1E2732","cat":"Urban Tech","application":"警示标签、功能织带"},
  {"id":"C014","pantone":"02-0008 TPG","name":"Night Glitch","zhName":"深夜故障","hex":"#161A1D","cat":"Urban Tech","application":"笔记本仓内衬"},
  {"id":"C015","pantone":"08-0038 TPG","name":"Anodized Grey","zhName":"阳极氧化灰","hex":"#6C6D70","cat":"Urban Tech","application":"印刷 LOGO、反光条"},
  {"id":"C016","pantone":"04-0021 TPG","name":"Lunar Surface","zhName":"月面灰","hex":"#3B3B3B","cat":"Urban Tech","application":"过渡配色"},
  {"id":"C017","pantone":"01-0006 TPG","name":"Onyx Matte","zhName":"哑光玛瑙","hex":"#0F0F0F","cat":"Urban Tech","application":"辅料配件"},
  {"id":"C018","pantone":"06-0028 TPG","name":"Dark Chrome","zhName":"暗铬","hex":"#4F4F4F","cat":"Urban Tech","application":"扣具"},
  {"id":"C019","pantone":"01-0005 TPG","name":"Borealis Black","zhName":"极光黑","hex":"#0D1117","cat":"Urban Tech","application":"织带"},
  {"id":"C020","pantone":"14-0067 TPG","name":"Liquid Metal","zhName":"液态金属","hex":"#BEBEBE","cat":"Urban Tech","application":"装饰细节"},
  {"id":"C021","pantone":"03-0010 TPG","name":"Navy Commuter","zhName":"通勤深蓝","hex":"#1B263B","cat":"Urban Outdoor","application":"主色调"},
  {"id":"C022","pantone":"07-0026 TPG","name":"Slate Blue","zhName":"石板蓝","hex":"#415A77","cat":"Urban Outdoor","application":"主色调"},
  {"id":"C023","pantone":"05-0018 TPG","name":"Stormy Sea","zhName":"暴雨海","hex":"#2D3E50","cat":"Urban Outdoor","application":"主色调"},
  {"id":"C024","pantone":"10-0044 TPG","name":"Pavement Grey","zhName":"铺路石灰","hex":"#778899","cat":"Urban Outdoor","application":"主色调"},
  {"id":"C025","pantone":"06-0028 TPG","name":"Gravel","zhName":"碎石色","hex":"#4F4F4F","cat":"Urban Outdoor","application":"主色调"},
  {"id":"C026","pantone":"04-0018 TPG","name":"Forest Shadow","zhName":"森影","hex":"#2F3E33","cat":"Urban Outdoor","application":"辅色搭配"},
  {"id":"C027","pantone":"05-0024 TPG","name":"Pine Needle","zhName":"松针绿","hex":"#3D5245","cat":"Urban Outdoor","application":"辅色搭配"},
  {"id":"C028","pantone":"07-0038 TPG","name":"Muddy Water","zhName":"泥水色","hex":"#706357","cat":"Urban Outdoor","application":"辅色搭配"},
  {"id":"C029","pantone":"12-0054 TPG","name":"Concrete Jungle","zhName":"混凝土","hex":"#95A5A6","cat":"Urban Outdoor","application":"辅色搭配"},
  {"id":"C030","pantone":"06-0029 TPG","name":"Warm Asphalt","zhName":"暖沥青","hex":"#525252","cat":"Urban Outdoor","application":"辅色搭配"},
  {"id":"C031","pantone":"05-0023 TPG","name":"Wet Pavement","zhName":"湿路面","hex":"#3E4444","cat":"Urban Outdoor","application":"点缀色"},
  {"id":"C032","pantone":"06-0021 TPG","name":"Harbor Blue","zhName":"港口蓝","hex":"#354B5E","cat":"Urban Outdoor","application":"点缀色"},
  {"id":"C033","pantone":"06-0027 TPG","name":"Iron Gate","zhName":"铁门灰","hex":"#4E5052","cat":"Urban Outdoor","application":"点缀色"},
  {"id":"C034","pantone":"07-0032 TPG","name":"Castlerock","zhName":"城堡岩","hex":"#595E62","cat":"Urban Outdoor","application":"点缀色"},
  {"id":"C035","pantone":"15-0070 TPG","name":"Rainy Day","zhName":"雨天灰","hex":"#C5C9C7","cat":"Urban Outdoor","application":"点缀色"},
  {"id":"C036","pantone":"04-0009 TPG","name":"Deep Teal","zhName":"深青色","hex":"#004D4D","cat":"Urban Outdoor","application":"内衬、拉链"},
  {"id":"C037","pantone":"06-0025 TPG","name":"Dusk Blue","zhName":"暮蓝","hex":"#405262","cat":"Urban Outdoor","application":"内衬、拉链"},
  {"id":"C038","pantone":"07-0037 TPG","name":"Walnut Shell","zhName":"核桃壳","hex":"#6E5F52","cat":"Urban Outdoor","application":"内衬、拉链"},
  {"id":"C039","pantone":"05-0028 TPG","name":"Urban Moss","zhName":"都市苔藓","hex":"#4B5320","cat":"Urban Outdoor","application":"内衬、拉链"},
  {"id":"C040","pantone":"04-0018 TPG","name":"Shadow Grey","zhName":"影灰","hex":"#333333","cat":"Urban Outdoor","application":"内衬、拉链"},
  {"id":"C041","pantone":"18-0085 TPG","name":"Alabaster","zhName":"雪花石膏","hex":"#F2F2F2","cat":"Minimalist","application":"大面积主色"},
  {"id":"C042","pantone":"18-0084 TPG","name":"Cloud Dancer","zhName":"云舞者","hex":"#F0EEE9","cat":"Minimalist","application":"大面积主色"},
  {"id":"C043","pantone":"17-0081 TPG","name":"Vapor White","zhName":"水汽白","hex":"#E5E4E2","cat":"Minimalist","application":"大面积主色"},
  {"id":"C044","pantone":"16-0078 TPG","name":"Oyster Shell","zhName":"牡蛎壳","hex":"#DCD9D4","cat":"Minimalist","application":"大面积主色"},
  {"id":"C045","pantone":"14-0070 TPG","name":"Silver Birch","zhName":"白桦色","hex":"#C9C1B9","cat":"Minimalist","application":"大面积主色"},
  {"id":"C046","pantone":"13-0064 TPG","name":"Pebble","zhName":"鹅卵石","hex":"#B7B1A9","cat":"Minimalist","application":"内饰、细节"},
  {"id":"C047","pantone":"16-0075 TPG","name":"Mist","zhName":"薄雾","hex":"#D3D3D3","cat":"Minimalist","application":"内饰、细节"},
  {"id":"C048","pantone":"09-0045 TPG","name":"Dovetail","zhName":"鸽羽色","hex":"#7E7D7A","cat":"Minimalist","application":"内饰、细节"},
  {"id":"C049","pantone":"12-0059 TPG","name":"Smoked Pearl","zhName":"烟珠色","hex":"#A7A6A2","cat":"Minimalist","application":"内饰、细节"},
  {"id":"C050","pantone":"19-0088 TPG","name":"Titanium White","zhName":"钛白","hex":"#FAFAFA","cat":"Minimalist","application":"内饰、细节"},
  {"id":"C051","pantone":"16-0078 TPG","name":"Nude Texture","zhName":"裸感肌理","hex":"#E3D7D3","cat":"Minimalist","application":"对比色、五金"},
  {"id":"C052","pantone":"13-0064 TPG","name":"Champagne Grey","zhName":"香槟灰","hex":"#B8B2A7","cat":"Minimalist","application":"对比色、五金"},
  {"id":"C053","pantone":"17-0080 TPG","name":"Glacier","zhName":"冰川白","hex":"#E1E8ED","cat":"Minimalist","application":"对比色、五金"},
  {"id":"C054","pantone":"16-0077 TPG","name":"Cool Grey 1C","zhName":"冷灰1号","hex":"#D9D9D6","cat":"Minimalist","application":"对比色、五金"},
  {"id":"C055","pantone":"11-0050 TPG","name":"Slate Tint","zhName":"浅石板色","hex":"#8B939C","cat":"Minimalist","application":"对比色、五金"},
  {"id":"C056","pantone":"06-0030 TPG","name":"Soft Charcoal","zhName":"软炭灰","hex":"#545454","cat":"Minimalist","application":"织带、扣具"},
  {"id":"C057","pantone":"14-0066 TPG","name":"Pure Zinc","zhName":"纯锌","hex":"#BABABA","cat":"Minimalist","application":"织带、扣具"},
  {"id":"C058","pantone":"18-0084 TPG","name":"Frost","zhName":"霜色","hex":"#EDF2F4","cat":"Minimalist","application":"织带、扣具"},
  {"id":"C059","pantone":"15-0073 TPG","name":"Pale Bone","zhName":"浅骨色","hex":"#D2CECA","cat":"Minimalist","application":"织带、扣具"},
  {"id":"C060","pantone":"18-0087 TPG","name":"Silk Matte","zhName":"哑光丝绸","hex":"#F5F5F5","cat":"Minimalist","application":"织带、扣具"},
  {"id":"C061","pantone":"09-0054 TPG","name":"Caramel","zhName":"焦糖色","hex":"#AF6E4D","cat":"Daily Casual","application":"帆布主料"},
  {"id":"C062","pantone":"10-0073 TPG","name":"Mustard Seed","zhName":"芥末籽","hex":"#E1AD01","cat":"Daily Casual","application":"帆布主料"},
  {"id":"C063","pantone":"09-0036 TPG","name":"Washed Denim","zhName":"水洗丹宁","hex":"#5D76A9","cat":"Daily Casual","application":"帆布主料"},
  {"id":"C064","pantone":"06-0044 TPG","name":"Brick Red","zhName":"砖红","hex":"#A52A2A","cat":"Daily Casual","application":"帆布主料"},
  {"id":"C065","pantone":"06-0045 TPG","name":"Olive Oil","zhName":"橄榄油","hex":"#808000","cat":"Daily Casual","application":"帆布主料"},
  {"id":"C066","pantone":"13-0067 TPG","name":"Canvas Khaki","zhName":"帆布卡其","hex":"#C3B091","cat":"Daily Casual","application":"水洗面料"},
  {"id":"C067","pantone":"13-0070 TPG","name":"Sand Dune","zhName":"沙丘","hex":"#D2B48C","cat":"Daily Casual","application":"水洗面料"},
  {"id":"C068","pantone":"10-0052 TPG","name":"Sage Leaf","zhName":"鼠尾草","hex":"#8F9779","cat":"Daily Casual","application":"水洗面料"},
  {"id":"C069","pantone":"11-0066 TPG","name":"Terra Cotta","zhName":"陶土","hex":"#E2725B","cat":"Daily Casual","application":"水洗面料"},
  {"id":"C070","pantone":"11-0082 TPG","name":"Amber","zhName":"琥珀","hex":"#FFBF00","cat":"Daily Casual","application":"水洗面料"},
  {"id":"C071","pantone":"06-0025 TPG","name":"Tidepool","zhName":"潮汐池","hex":"#3D5A5A","cat":"Daily Casual","application":"内衬、拉链头"},
  {"id":"C072","pantone":"10-0070 TPG","name":"Harvest Gold","zhName":"收获金","hex":"#DAA520","cat":"Daily Casual","application":"内衬、拉链头"},
  {"id":"C073","pantone":"05-0019 TPG","name":"Indigo","zhName":"靛蓝","hex":"#2E4053","cat":"Daily Casual","application":"内衬、拉链头"},
  {"id":"C074","pantone":"09-0057 TPG","name":"Copper","zhName":"红铜","hex":"#B87333","cat":"Daily Casual","application":"内衬、拉链头"},
  {"id":"C075","pantone":"16-0079 TPG","name":"Oatmeal","zhName":"燕麦","hex":"#E3D9C6","cat":"Daily Casual","application":"内衬、拉链头"},
  {"id":"C076","pantone":"07-0043 TPG","name":"Chestnut","zhName":"栗色","hex":"#954535","cat":"Daily Casual","application":"缝线、点缀"},
  {"id":"C077","pantone":"03-0009 TPG","name":"Denim Dark","zhName":"深色丹宁","hex":"#152238","cat":"Daily Casual","application":"缝线、点缀"},
  {"id":"C078","pantone":"16-0084 TPG","name":"Wheat Field","zhName":"麦田","hex":"#F5DEB3","cat":"Daily Casual","application":"缝线、点缀"},
  {"id":"C079","pantone":"15-0082 TPG","name":"Peach Fuzz","zhName":"柔和桃","hex":"#FFBE98","cat":"Daily Casual","application":"缝线、点缀"},
  {"id":"C080","pantone":"14-0056 TPG","name":"Sky Blue","zhName":"天蓝","hex":"#87CEEB","cat":"Daily Casual","application":"缝线、点缀"},
  {"id":"C081","pantone":"09-0066 TPG","name":"Autumn Leaf","zhName":"秋叶","hex":"#D68910","cat":"Yama Style","application":"主料 (尼龙/帆布)"},
  {"id":"C082","pantone":"04-0016 TPG","name":"Deep Forest","zhName":"深林","hex":"#145A32","cat":"Yama Style","application":"主料 (尼龙/帆布)"},
  {"id":"C083","pantone":"05-0024 TPG","name":"Earth Brown","zhName":"土褐","hex":"#483C32","cat":"Yama Style","application":"主料 (尼龙/帆布)"},
  {"id":"C084","pantone":"09-0062 TPG","name":"Ochre","zhName":"赭石","hex":"#CC7722","cat":"Yama Style","application":"主料 (尼龙/帆布)"},
  {"id":"C085","pantone":"10-0050 TPG","name":"Moss Green","zhName":"苔藓绿","hex":"#8A9A5B","cat":"Yama Style","application":"主料 (尼龙/帆布)"},
  {"id":"C086","pantone":"12-0085 TPG","name":"Midnight Sun","zhName":"午夜阳","hex":"#FFD700","cat":"Yama Style","application":"抽绳、织带点缀"},
  {"id":"C087","pantone":"06-0030 TPG","name":"Plum","zhName":"李子红","hex":"#673147","cat":"Yama Style","application":"抽绳、织带点缀"},
  {"id":"C088","pantone":"07-0060 TPG","name":"Rustic Orange","zhName":"铁锈橙","hex":"#D35400","cat":"Yama Style","application":"抽绳、织带点缀"},
  {"id":"C089","pantone":"09-0027 TPG","name":"Lake Blue","zhName":"湖蓝","hex":"#2E86C1","cat":"Yama Style","application":"抽绳、织带点缀"},
  {"id":"C090","pantone":"07-0040 TPG","name":"Sandstone","zhName":"砂岩","hex":"#766344","cat":"Yama Style","application":"抽绳、织带点缀"},
  {"id":"C091","pantone":"05-0017 TPG","name":"Spruce","zhName":"云杉蓝","hex":"#2C3E50","cat":"Yama Style","application":"内衬、拼接"},
  {"id":"C092","pantone":"06-0035 TPG","name":"Cedar","zhName":"雪松","hex":"#6D4C41","cat":"Yama Style","application":"内衬、拼接"},
  {"id":"C093","pantone":"07-0033 TPG","name":"Fern","zhName":"蕨草","hex":"#4F7942","cat":"Yama Style","application":"内衬、拼接"},
  {"id":"C094","pantone":"10-0075 TPG","name":"Sunset Glow","zhName":"落日余晖","hex":"#FD7E14","cat":"Yama Style","application":"内衬、拼接"},
  {"id":"C095","pantone":"05-0022 TPG","name":"Granite Grey","zhName":"花岗岩","hex":"#3E3E3E","cat":"Yama Style","application":"内衬、拼接"},
  {"id":"C096","pantone":"07-0033 TPG","name":"Wild Berry","zhName":"野果色","hex":"#8B008B","cat":"Yama Style","application":"拉链、扣件"},
  {"id":"C097","pantone":"05-0020 TPG","name":"Slate Green","zhName":"石板绿","hex":"#2F4F4F","cat":"Yama Style","application":"拉链、扣件"},
  {"id":"C098","pantone":"13-0074 TPG","name":"Tumbleweed","zhName":"风滚草","hex":"#DEB887","cat":"Yama Style","application":"拉链、扣件"},
  {"id":"C099","pantone":"12-0042 TPG","name":"Alpine Blue","zhName":"高山蓝","hex":"#6495ED","cat":"Yama Style","application":"拉链、扣件"},
  {"id":"C100","pantone":"05-0030 TPG","name":"Bark","zhName":"树皮","hex":"#5D4037","cat":"Yama Style","application":"拉链、扣件"},
  {"id":"C101","pantone":"08-0068 TPG","name":"Rescue Orange","zhName":"救援橙","hex":"#FF4500","cat":"Outdoor Tech","application":"警示标识、内衬"},
  {"id":"C102","pantone":"12-0086 TPG","name":"Safety Yellow","zhName":"荧光黄","hex":"#EFFF00","cat":"Outdoor Tech","application":"警示标识、内衬"},
  {"id":"C103","pantone":"11-0078 TPG","name":"Electric Volt","zhName":"电力绿","hex":"#CEFF00","cat":"Outdoor Tech","application":"警示标识、内衬"},
  {"id":"C104","pantone":"01-0001 TPG","name":"Abyss Blue","zhName":"深渊蓝","hex":"#000C1F","cat":"Outdoor Tech","application":"警示标识、内衬"},
  {"id":"C105","pantone":"16-0077 TPG","name":"Glacier Ice","zhName":"冰川冰","hex":"#D0F0C0","cat":"Outdoor Tech","application":"警示标识、内衬"},
  {"id":"C106","pantone":"03-0033 TPG","name":"Magma","zhName":"岩浆","hex":"#8B0000","cat":"Outdoor Tech","application":"主料 (防水/耐磨)"},
  {"id":"C107","pantone":"06-0060 TPG","name":"Siren Red","zhName":"警笛红","hex":"#FF0000","cat":"Outdoor Tech","application":"主料 (防水/耐磨)"},
  {"id":"C108","pantone":"06-0030 TPG","name":"Night Vision","zhName":"夜视绿","hex":"#00FF00","cat":"Outdoor Tech","application":"主料 (防水/耐磨)"},
  {"id":"C109","pantone":"19-0089 TPG","name":"Polar White","zhName":"极地白","hex":"#FBFCF8","cat":"Outdoor Tech","application":"主料 (防水/耐磨)"},
  {"id":"C110","pantone":"12-0054 TPG","name":"Tundra Grey","zhName":"冻原灰","hex":"#95A5A6","cat":"Outdoor Tech","application":"主料 (防水/耐磨)"},
  {"id":"C111","pantone":"04-0014 TPG","name":"Storm Shadow","zhName":"风暴影","hex":"#243447","cat":"Outdoor Tech","application":"拼接、补强"},
  {"id":"C112","pantone":"08-0031 TPG","name":"Ultraviolet","zhName":"紫外线","hex":"#5F4B8B","cat":"Outdoor Tech","application":"拼接、补强"},
  {"id":"C113","pantone":"10-0063 TPG","name":"Acid Green","zhName":"酸性绿","hex":"#B0BF1A","cat":"Outdoor Tech","application":"拼接、补强"},
  {"id":"C114","pantone":"03-0004 TPG","name":"Deep Sea Blue","zhName":"深海蓝","hex":"#002366","cat":"Outdoor Tech","application":"拼接、补强"},
  {"id":"C115","pantone":"03-0013 TPG","name":"Volcanic Rock","zhName":"火山岩","hex":"#252525","cat":"Outdoor Tech","application":"拼接、补强"},
  {"id":"C116","pantone":"10-0076 TPG","name":"Solar Flare","zhName":"太阳耀斑","hex":"#FF8C00","cat":"Outdoor Tech","application":"拉链、抽绳"},
  {"id":"C117","pantone":"11-0022 TPG","name":"Oxygen Blue","zhName":"氧气蓝","hex":"#00BFFF","cat":"Outdoor Tech","application":"拉链、抽绳"},
  {"id":"C118","pantone":"04-0019 TPG","name":"Stealth Camo","zhName":"隐形迷彩基色","hex":"#353839","cat":"Outdoor Tech","application":"拉链、抽绳"},
  {"id":"C119","pantone":"10-0062 TPG","name":"High-Viz Pink","zhName":"高视度粉","hex":"#FF1493","cat":"Outdoor Tech","application":"拉链、抽绳"},
  {"id":"C120","pantone":"09-0031 TPG","name":"Cold Steel","zhName":"冷钢蓝","hex":"#4682B4","cat":"Outdoor Tech","application":"拉链、抽绳"},
  {"id":"C121","pantone":"05-0032 TPG","name":"Coyote Dark","zhName":"深狼棕","hex":"#654321","cat":"Tactical","application":"Cordura 主料、MOLLE织带"},
  {"id":"C122","pantone":"05-0025 TPG","name":"Ranger Green","zhName":"游骑兵绿","hex":"#444C38","cat":"Tactical","application":"Cordura 主料、MOLLE织带"},
  {"id":"C123","pantone":"06-0030 TPG","name":"Wolf Grey","zhName":"狼灰","hex":"#53565A","cat":"Tactical","application":"Cordura 主料、MOLLE织带"},
  {"id":"C124","pantone":"12-0067 TPG","name":"Desert Sand","zhName":"沙漠沙","hex":"#C2B280","cat":"Tactical","application":"Cordura 主料、MOLLE织带"},
  {"id":"C125","pantone":"10-0055 TPG","name":"Tan 499","zhName":"美军标卡其","hex":"#A58B6F","cat":"Tactical","application":"Cordura 主料、MOLLE织带"},
  {"id":"C126","pantone":"08-0044 TPG","name":"Multicam Green","zhName":"迷彩绿","hex":"#7C7C52","cat":"Tactical","application":"副料、拼接"},
  {"id":"C127","pantone":"04-0020 TPG","name":"Olive Drab","zhName":"橄榄褐","hex":"#3D3635","cat":"Tactical","application":"副料、拼接"},
  {"id":"C128","pantone":"08-0043 TPG","name":"Flat Dark Earth","zhName":"暗土色","hex":"#7E6D5A","cat":"Tactical","application":"副料、拼接"},
  {"id":"C129","pantone":"02-0009 TPG","name":"Special Ops Black","zhName":"特种黑","hex":"#1A1A1A","cat":"Tactical","application":"副料、拼接"},
  {"id":"C130","pantone":"04-0016 TPG","name":"Gunmetal","zhName":"枪色","hex":"#2C3539","cat":"Tactical","application":"副料、拼接"},
  {"id":"C131","pantone":"06-0035 TPG","name":"Field Drab","zhName":"野战褐","hex":"#6C541E","cat":"Tactical","application":"内衬、网布"},
  {"id":"C132","pantone":"08-0045 TPG","name":"Khaki Drill","zhName":"卡其斜纹","hex":"#827839","cat":"Tactical","application":"内衬、网布"},
  {"id":"C133","pantone":"10-0045 TPG","name":"Urban Camo Grey","zhName":"都市迷彩灰","hex":"#808080","cat":"Tactical","application":"内衬、网布"},
  {"id":"C134","pantone":"10-0047 TPG","name":"Battleship Grey","zhName":"舰艇灰","hex":"#848482","cat":"Tactical","application":"内衬、网布"},
  {"id":"C135","pantone":"01-0004 TPG","name":"Night Stalker","zhName":"夜袭者","hex":"#0B0B0B","cat":"Tactical","application":"内衬、网布"},
  {"id":"C136","pantone":"14-0076 TPG","name":"Savannah","zhName":"萨凡纳","hex":"#E1C699","cat":"Tactical","application":"扣具、拉链"},
  {"id":"C137","pantone":"12-0066 TPG","name":"Earth Khaki","zhName":"大地卡其","hex":"#BDB76B","cat":"Tactical","application":"扣具、拉链"},
  {"id":"C138","pantone":"10-0052 TPG","name":"Foliage Green","zhName":"叶绿","hex":"#8F9779","cat":"Tactical","application":"扣具、拉链"},
  {"id":"C139","pantone":"05-0022 TPG","name":"Commando","zhName":"突击队色","hex":"#3B444B","cat":"Tactical","application":"扣具、拉链"},
  {"id":"C140","pantone":"07-0047 TPG","name":"Dusty Brown","zhName":"落灰褐","hex":"#966919","cat":"Tactical","application":"扣具、拉链"}
];
